### PR TITLE
Dhv3

### PR DESCRIPTION
**Pull request by shadowattackq**
try to merge dihv3 and master

### CODE REVIEW

**Comment by eugenevanstaden** [comment]
> try to merge dihv3 and master

Why?

**Comment by shadowattackq** [comment]
master branch does not implement the "OAuth connectionstring" change made to Dhv3.  Pipeline fails everytime without it.

**Comment by shadowattackq** [comment]
https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/authenticate-office365-deprecation

**Comment by shadowattackq** [comment]
https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/authenticate-office365-deprecation

**Pull request closed without merging**
